local args = {...}

local function usage()
    io.stderr:write("Usage: build.sh <entry.lua> [output.lua]\n")
    os.exit(1)
end

local function dirname(path)
    return (path:gsub("/+$", ""):match("^(.*)/[^/]*$")) or "."
end

local function basename(path)
    return path:match("([^/]+)$") or path
end

local function normalize(path)
    local parts = {}

    for part in path:gmatch("[^/]+") do
        if part == ".." then
            table.remove(parts)
        elseif part ~= "." and part ~= "" then
            table.insert(parts, part)
        end
    end

    local prefix = path:sub(1, 1) == "/" and "/" or ""
    return prefix .. table.concat(parts, "/")
end

local function output_name_for_entry(src_root, entry_path)
    local relative = entry_path:sub(#src_root + 2)
    local file_name = basename(relative)
    local output_name

    if file_name == "index.lua" then
        output_name = dirname(relative)
    else
        output_name = relative:gsub("%.lua$", "")
    end

    output_name = output_name:gsub("[/%-]+", "_")
    return output_name .. ".lua"
end

local function read_file(path)
    local file = assert(io.open(path, "r"))
    local contents = file:read("*a")
    file:close()
    return contents
end

local function write_file(path, contents)
    local file = assert(io.open(path, "w"))
    file:write(contents)
    file:close()
end

local function mkdir_p(path)
    local ok = os.execute(('mkdir -p "%s"'):format(path:gsub('"', '\\"')))
    if ok ~= true and ok ~= 0 then
        error("Unable to create directory: " .. path)
    end
end

local function find_src_root(entry_path)
    local marker = "/src/"
    local start_at = entry_path:find(marker, 1, true)

    if start_at then
        return entry_path:sub(1, start_at + #marker - 2)
    end

    error("Entry file must be inside a src directory: " .. entry_path)
end

local function module_to_path(src_root, current_dir, module_name)
    local candidates = {}
    local module_path = module_name:gsub("%.", "/")

    table.insert(candidates, normalize(src_root .. "/" .. module_path .. ".lua"))
    table.insert(candidates, normalize(src_root .. "/" .. module_path .. "/index.lua"))

    if not module_name:find("%.", 1, false) then
        table.insert(candidates, normalize(current_dir .. "/" .. module_name .. ".lua"))
        table.insert(candidates, normalize(current_dir .. "/" .. module_name .. "/index.lua"))
    end

    for _, candidate in ipairs(candidates) do
        local file = io.open(candidate, "r")
        if file then
            file:close()
            return candidate
        end
    end

    return nil
end

local function collect_requires(contents)
    local requires = {}

    for quote, module_name in contents:gmatch("require%s*%(?%s*(['\"])([%w_%.%-/]+)%1%s*%)?") do
        table.insert(requires, module_name)
    end

    return requires
end

local entry = args[1]
if not entry then
    usage()
end

entry = normalize(entry)

local src_root = find_src_root(entry)
local build_root = normalize(dirname(src_root) .. "/build")
local output = args[2]

if output then
    output = normalize(output)
else
    output = normalize(build_root .. "/" .. output_name_for_entry(src_root, entry))
end

local ordered_modules = {}
local seen = {}

local function visit(path)
    path = normalize(path)
    local contents = read_file(path)
    local current_dir = dirname(path)

    for _, module_name in ipairs(collect_requires(contents)) do
        local dep_path = module_to_path(src_root, current_dir, module_name)

        if dep_path and dep_path ~= entry and not seen[dep_path] then
            seen[dep_path] = true
            visit(dep_path)
            table.insert(ordered_modules, {
                name = module_name,
                path = dep_path,
                contents = read_file(dep_path)
            })
        end
    end
end

visit(entry)

local output_parts = {
    "-- Bundled from " .. entry,
    "-- Generated by backend/src/scripts/build.sh",
    "",
    "package = package or {}",
    "package.preload = package.preload or {}",
    ""
}

for _, module in ipairs(ordered_modules) do
    table.insert(output_parts, ("package.preload[%q] = function(...)"):format(module.name))
    table.insert(output_parts, ("-- Source: %s"):format(module.path))
    table.insert(output_parts, (module.contents:gsub("%s*$", "")))
    table.insert(output_parts, "end")
    table.insert(output_parts, "")
end

table.insert(output_parts, ("-- Entry: %s"):format(entry))
table.insert(output_parts, (read_file(entry):gsub("%s*$", "")))
table.insert(output_parts, "")

mkdir_p(dirname(output))
write_file(output, table.concat(output_parts, "\n"))

print(output)
